### PR TITLE
WIP: Rewrote mkroosevelt to be a Yeoman Generator

### PR DESCRIPTION
**Pull request by alallier**
Rewrote mkroosevelt to be a [Yeoman Generator](http://yeoman.io/).

We should also consider [registering ](http://yeoman.io/generators/) our generator with Yeoman so that someone could install Roosevelt with just [`yo`](https://www.npmjs.com/package/yo) alone (instead of also having to install mkroosevelt)

### CODE REVIEW

**Comment by alallier** [comment]
If/when this is accepted we will definitely want to add travis to mkroosevelt because there is a whole suite of unit tests to go with the yeoman generator

**Comment by alallier** [comment]
Also, remove bin folder

**Comment by alallier** [comment]
Made new updates.

* Removed number of prompt configs
* Added SSL generation
* Removed mkroosevelt script file
* Renamed yo command so that you generate a new app by calling `yo roosevelt`
* Removed bin directory
* Fixed ESlinting
* Warn user of installing in current directory and allow them to specify alternate path
* Add closing message telling the user where to go if they would like to configure their app more manually

**Comment by alallier** [comment]
Note to self: Add unit test for new ssl regeneration prompt and generation

**Comment by kethinov** [comment]
Question changes:
- ✎ `Install in current directory? If not specify an alternative path (relative to current working directory 'newDirectory/test' or absoulte '/Users/jsmith' (Unix) 'C:\Users\jsmith\Documents\newDirectory\' (Windows)`
  - → `Where would you like to generate a new Roosevelt app?`
- ✎ `Your project name`
  - → `Your app's name:`
  - Default for `App name` should be ` my-roosevelt-sample-app`
- ✎ `Standard Install? Selecting no will walk you through an advanced install`
  - → `Generate a standard config or customize it now?`
  - Instead of a `Y/n` here, give the user a choice of "standard" or "customize"
- ✎ `Port: The port your app will run on. Can also be defined using NODE_PORT environment variable`
  - → `HTTP port your app will run on:`
  - Also move this question after the HTTPS questions
- ✎ `HTTPS: Run an HTTPS server using Roosevelt.`
  - → `Use HTTPS? (N/y)`
- ✎ `Would you like to generate ssl certs after prompting?`
  - → `Generate SSL certs now? (N/y)`
  - Also move to the question to after the other HTTPS questions
  - If `y`, it should immediately trigger the SSL cert questions
- ✎ `HTTPS Only: If running an HTTPS server, determines whether or not the default HTTP server will be disabled`
  - → `Use HTTPS only? (Disable HTTP?)`
- ✎ `HTTPS Port: The port your app will run an HTTPS server on, if enabled.`
  - → `HTTPS port your app will run on:`
- ✎ `Pfx: Specify whether or not your app will use pfx or standard certification`
  - → `Use .pfx or .cert for SSL connections?`
  - Instead of a `true/false` here, give the user a choice of ".pfx" or ".cert"
- ✎ `Passphrase: Supply the HTTPS server with the password for the certificate being used, if necessary.`
  - → `Passphrase for HTTPS server to use with the SSL cert (optional):`
- ✎ `Models Path: Relative path on filesystem to where your model files are located.`
  - → `Where should data model files be located in the app's directory structure?`
- ✎ `Views Path: Relative path on filesystem to where your view files are located.`
  - → `Where should view (HTML template) files be located in the app's directory structure?`
- ✎ `Controllers Path: Relative path on filesystem to where your controller files are located.`
  - → `Where should controller (Express route) files be located in the app's directory structure?`
- Do not automatically run `npm i` at the end.

Change the view engine giant blob question to a series of new questions:
- `Do you want to use a HTML templating engine? (Y/n)`
- If `n`, configure to use "none" in package.json.
- If `Y`, see below...
- `What templating engine do you want to use? (Supply npm module name.)` Default: `teddy`
- Automatically add the selected npm module to package.json. Include logic to verify that the package exists and that it has Express support if you can figure out a way to do that.
- `What file extension do you want [chosen templating engine] to use?` Default: `html`
- `Do you want to support an additional templating engine? (N/y)`
- If `Y`, go back to the first question.

And change the final message to:

```
Your app "[app name chosen by the user]" has been generated.

To run the app:
- Install dependencies: `npm i`
- To run in dev mode: `npm run dev`
- To run in prod mode: `npm run prod`
- Once running, visit http://localhost:[port number chosen by the user]

To make further changes to the config, edit package.json. See https://github.com/kethinov/roosevelt#configure-your-app-with-parameters for information on the configuration options.
```

Some more problematic questions:
- `Key Path`
- `Ca`
- `Request Cert`
- `Reject Unauthorized`

Those are all pretty technical and could use clearer questions. (And yeah, I know the roosevelt docs need the same clearing up.)

Likewise, when generating the SSL certs:
- `Enter the two-character denomination of your country`
- `Enter the name of your state or province, if applicable`
- `Enter the name of your city`
- `Enter the legal name of your organization, if applicable`
- `Enter the organizational unit represented by the site, if applicable (e.g. Internet Sales)`
- `Enter any alternative URI the certificate would be active for`
- `Enter the IP address the certificate would be active for`

All of those could use more context walking the user through the best practices.

If there are any other questions or messages in here I missed, be sure you alter those to match the tone and style of my revisions.

**Comment by alallier** [comment]
@Autre31415 When setting the default app name you can change use `My Roosevelt Sample App` instead of `my-roosevelt-sample-app` because then it will show up in the HTML properly because I dash it before saving it into the package.json.

**Comment by alallier** [comment]
During the standard install, the view engine is setup incorrectly. The `package.json` when using the generator on standard creates this `"viewEngine": "teddy: html"` but it should be `"viewEngine": "html: teddy"`

**Comment by alallier** [comment]
I believe the only thing waiting on this is the SSl re-wording. Can you confirm @Autre31415?

Also, I don't think we have figured out what we want to do with the unit tests yet?

**Pull request merged**
