### PR TITLE
Replace Nodemon with Supervisor (Closes Issue #5)

### PR DESCRIPTION
**Pull request by alallier**
(Closes Issue #5)

### CODE REVIEW

**Comment by kethinov** [comment]
A few issues with this:

1. New `-k` flag to do instant kill is not passed.
2. It doesn't seem to be ignoring `statics/.build`
3. When I added `-k` flag manually in testing it produced a restart loop (probably because of the second issue).

```
npm run dev

> sample-app@0.1.0 dev /Users/kethinov/Desktop/sup
> supervisor -k -e js,json,less,html --ignore statics/.build/ --ignore public/ -- app.js -dev


Running node-supervisor with
  program 'app.js -dev'
  --watch '.'
  --ignore 'public/'
  --extensions 'js,json,less,html'
  --exec 'node'

Starting child process with 'node app.js -dev'
Ignoring directory '/Users/kethinov/Desktop/sup/public'.
Watching directory '/Users/kethinov/Desktop/sup' for changes.
Press rs for restarting the process.
sample-app server listening on port 43711 (development mode)
sample-app writing new JS file /Users/kethinov/Desktop/sup/statics/.build/js/main.js
crashing child with SIGKILL
Starting child process with 'node app.js -dev'
sample-app server listening on port 43711 (development mode)
sample-app writing new JS file /Users/kethinov/Desktop/sup/statics/.build/js/main.js
crashing child with SIGKILL
Starting child process with 'node app.js -dev'
sample-app server listening on port 43711 (development mode)
sample-app writing new JS file /Users/kethinov/Desktop/sup/statics/.build/js/main.js
```

**Comment by alallier** [comment]
Updated based on your feedback.

**Comment by kethinov** [comment]
This still doesn't work correctly.

In my testing it has to be formatted like this:

```
    "prod": "supervisor -k -e js,json,less,html -i statics/.build/,public/ -- app.js -prod",
    "dev": "supervisor -k -e js,json,less,html -i statics/.build/,public/ -- app.js -dev",
```

**Comment by alallier** [comment]
Updated, sorry for the confusion/hassle.

**Pull request merged**
